server:
  port: 8888
spring:
  application:
    name: moive
  datasource:
    url: jdbc:mysql://localhost:3306/moive?useUnicode=true&characterEncoding=utf-8&serverTimeZone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 1000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
      static-locations: classpath:/static/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: mv_